# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'StickerModuleExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "Sticker", :path => '/Users/huseyinkapi/Projects/OAK/Sticker/'
  # Pods for StickerModuleExample

end
